### ISSUE TITLE
External unmount does not finish the the mount task

### ISSUE THREAD

**Issue by wvffle** [Sherlock-Holo/fuse3#102]
I've tested both my filesystem and the `path_memfs` example and it seems like, when I do `umount mount-point` in terminal, it does not finish the mount task, leaving the program running.

I'm using tokio runtime.

**Comment by Sherlock-Holo** [comment]
it looks like when using unprivileged mode, the session can't realize the fs is umounted by umount cmd

**Comment by wvffle** [comment]
My previous implementation with `fuser` crate didn't have such issue. Maybe they found a way to handle it?

**Comment by mash-graz** [comment]
> My previous implementation with fuser crate didn't have such issue. Maybe they found a way to handle it?

I just published #107 as a solution for this issue.

In `fuser` it's much easier handled by a simple blocking `read()` call, which will report the unmount event by returning an `ENODEV` result. In `fuse3` we have to instruct the async file io polling mechanism in advance, that we are not only waiting for incoming requests resp.  `readable` state changes, but also want to get `ERROR` notifications. Otherwise, we will never get this unmount indicator.

**Comment by Sherlock-Holo** [comment]
try 0.7.3 version, it merged #107 and should fix this problem
